#!/usr/bin/env python3
"""navadhiti hygiene — repository baseline verifier.

Answers one question: does this repository meet the baseline it enforces on
other repositories? One command, one verdict, every criterion — so that
"is this repository healthy?" has exactly one answer source.

    python tools/verify_baseline.py

Governed by specs/001-fix-own-repo-hygiene/contracts/verify-baseline-cli.md.
The shape of the internal entities is fixed by that feature's data-model.md.

Stdlib only, on purpose. One criterion is "the test suite is green", so a
verifier that imported a third-party package could be disabled by the very
broken `pip install` it exists to catch. It reads git-tracked state, writes
nothing, and works from any working directory.

Exit codes are the contract's most important guarantee:

    0  every criterion passed
    1  the repository does not meet its baseline
    2  the verifier could not run — NOT a statement about the repository

Nothing here ever prints a denied identifier, a credential value, or a token
fragment. Findings reference a path, a line number, a count, or a pattern
name, so a report can be pasted into a ticket without re-exporting the secret
it found.
"""

from __future__ import annotations

import base64
import os
import re
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable, Iterable, Iterator, Optional

# --------------------------------------------------------------------------
# Constants
# --------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent.parent

# Directories whose contents are one developer's environment, never source.
# Checked against every directory component of a tracked path.
ENV_DIR_NAMES = frozenset({
    "venv", ".venv", "env", "ENV", "virtualenv", ".tox", "node_modules",
})

# Directories never worth scanning for denied identifiers: version-control
# internals and generated bytecode. Not an exemption — just noise.
SCAN_SKIP_PARTS = frozenset({".git", "__pycache__", "venv", ".venv"})

# How many environment files the repository tracked before this baseline.
# Reported next to the live count so the number is comparable over time.
HISTORICAL_ENV_FILE_COUNT = 1989

# The declared test runner (research.md D1). A missing runner and a failing
# suite are different failures and are reported as such.
TEST_RUNNER = "pytest"

# --- The no-real-data denylist -------------------------------------------
# Real identifiers scrubbed from tracked content by FR-024. They are stored
# base64-encoded for one reason: this file is itself tracked content, so a
# plaintext entry would make the check match its own source and fail forever.
#
# Adding an identifier is a deliberate, reviewable edit. Encode it with:
#     python -c "import base64,sys;print(base64.b64encode(sys.argv[1].encode()).decode())" '<id>'
# and append a line. Decoding happens once, at import, into the module-level
# tuple below — never back into source.
DENIED_IDENTIFIERS_B64: tuple[str, ...] = (
    "cmVsZWFzZXNAbmF2YWRoaXRpLmNvbQ==",  # real Office365 mailbox address
    "bmF2YWRoaXRpLmF0bGFzc2lhbi5uZXQ=",  # external tenant domain
)

DENIED_IDENTIFIERS: tuple[str, ...] = tuple(
    base64.b64decode(encoded).decode("utf-8")
    for encoded in DENIED_IDENTIFIERS_B64
)

# Keys that make a project-metadata entry "live" rather than a sample
# (FR-023). The check asks whether the key is *commented*, never which file it
# sits in — a live budget in tests/ is still a violation.
LIVE_PROJECT_KEYS = ("budget", "headcount", "timesheet_code")

PROJECTS_CONFIG = "config/projects.yaml"
README = "README.md"
RECORD = "CONFIDENTIALITY.md"
NOTICE = "NOTICE"
DEPENDABOT = ".github/dependabot.yml"
PRE_COMMIT_CONFIG = ".pre-commit-config.yaml"
SECRETS_BASELINE = ".secrets.baseline"

# Confidentiality record headings, in the order the contract requires.
REQUIRED_RECORD_SECTIONS = (
    "Decision",
    "Date",
    "Accountable Owner",
    "Rationale",
    "What This Repository Must Never Contain",
    "Accepted Exposures",
    "Revisit Triggers",
    "Related",
)

# FR-033. Printed on every run, in every medium, so that a green run is never
# read as "this stopped a merge".
DISCLAIMER = "this run reports only; it does not prevent merges"

STATUS_PASS = "pass"
STATUS_FAIL = "fail"
STATUS_UNVERIFIABLE = "unverifiable"

EXIT_PASS = 0
EXIT_FAIL = 1
EXIT_CANNOT_RUN = 2

CRITERION_ID_RE = re.compile(r"^[a-z0-9-]+$")


class VerifierCannotStart(RuntimeError):
    """The verifier itself could not run. Exit 2, never a repository verdict."""


# --------------------------------------------------------------------------
# Entities (data-model.md)
# --------------------------------------------------------------------------

@dataclass(frozen=True)
class Criterion:
    """One baseline assertion the verifier evaluates."""

    id: str
    label: str
    requirements: tuple[str, ...]
    determination: str
    cannot_determine_action: str
    check: Callable[["Repository"], "CriterionResult"]

    def __post_init__(self) -> None:
        if not CRITERION_ID_RE.match(self.id):
            raise VerifierCannotStart(
                f"criterion id {self.id!r} must be kebab-case ([a-z0-9-]+)")
        if not self.requirements:
            raise VerifierCannotStart(
                f"criterion {self.id!r} traces to no requirement; that is scope creep")
        if self.determination != "observed":
            # Rejected at startup, not at evaluation time: a criterion whose
            # determination is undecided cannot honestly produce a verdict.
            raise VerifierCannotStart(
                f"criterion {self.id!r} has determination {self.determination!r}; "
                "only 'observed' is permitted in this milestone")
        if self.cannot_determine_action not in ("report_unverifiable", "fail"):
            raise VerifierCannotStart(
                f"criterion {self.id!r} has an unknown cannot_determine_action "
                f"{self.cannot_determine_action!r}")


@dataclass(frozen=True)
class CriterionResult:
    """The outcome of evaluating one Criterion against the working tree."""

    criterion_id: str
    status: str
    detail: str
    evidence: tuple[str, ...] = ()
    observed: dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.status not in (STATUS_PASS, STATUS_FAIL, STATUS_UNVERIFIABLE):
            raise ValueError(
                f"criterion {self.criterion_id!r} produced status {self.status!r}")
        if self.status == STATUS_FAIL and not self.detail:
            raise ValueError(
                f"criterion {self.criterion_id!r} failed without saying why")
        if self.status == STATUS_UNVERIFIABLE and not self.detail:
            raise ValueError(
                f"criterion {self.criterion_id!r} could not be evaluated without "
                "naming what was missing")


@dataclass(frozen=True)
class BaselineReport:
    """The complete result of one verifier run."""

    criteria: tuple[CriterionResult, ...]
    verdict: str
    commit: Optional[str]
    generated_at: str
    blocking: bool = False

    @property
    def failed(self) -> int:
        return sum(1 for r in self.criteria if r.status != STATUS_PASS)


# --------------------------------------------------------------------------
# Repository — read-only view of git-tracked state
# --------------------------------------------------------------------------

class Repository:
    """A read-only handle on the checkout.

    Holds nothing that outlives one run and writes nothing at all, which is
    what lets the verifier be run on a colleague's checkout without asking and
    what makes two runs against one commit produce identical output.
    """

    def __init__(self, root: Path) -> None:
        self.root = root
        self._tracked: Optional[tuple[str, ...]] = None
        self._commit: Optional[str] = None
        self._commit_resolved = False

    # -- git -------------------------------------------------------------

    def _git(self, *args: str) -> str:
        try:
            proc = subprocess.run(
                ["git", "-C", str(self.root), *args],
                capture_output=True, text=True, timeout=60,
            )
        except FileNotFoundError as exc:
            raise VerifierCannotStart("git is not available on PATH") from exc
        except subprocess.TimeoutExpired as exc:
            raise VerifierCannotStart(f"git {' '.join(args)} timed out") from exc
        if proc.returncode != 0:
            raise VerifierCannotStart(
                f"git {' '.join(args)} failed: {proc.stderr.strip()}")
        return proc.stdout

    def tracked_files(self) -> tuple[str, ...]:
        """Repository-relative POSIX paths of every tracked file, sorted."""
        if self._tracked is None:
            out = self._git("ls-files", "-z")
            self._tracked = tuple(sorted(p for p in out.split("\0") if p))
        return self._tracked

    def commit_sha(self) -> Optional[str]:
        """Current commit SHA, or None outside a repository.

        Prints as absent rather than as a placeholder: a fabricated SHA would
        make two different states look identical in the output.
        """
        if not self._commit_resolved:
            try:
                self._commit = self._git("rev-parse", "HEAD").strip() or None
            except VerifierCannotStart:
                self._commit = None
            self._commit_resolved = True
        return self._commit

    # -- filesystem ------------------------------------------------------

    def path(self, relative: str) -> Path:
        return self.root / relative

    def exists(self, relative: str) -> bool:
        return self.path(relative).is_file()

    def read_text(self, relative: str) -> str:
        return self.path(relative).read_text(encoding="utf-8", errors="replace")

    def tracked_text_files(self) -> Iterator[tuple[str, list[str]]]:
        """Yield (path, lines) for every tracked text file worth scanning."""
        for relative in self.tracked_files():
            if any(part in SCAN_SKIP_PARTS for part in Path(relative).parts):
                continue
            lines = self._read_lines(relative)
            if lines is not None:
                yield relative, lines

    def _read_lines(self, relative: str) -> Optional[list[str]]:
        target = self.path(relative)
        try:
            raw = target.read_bytes()
        except (OSError, ValueError):
            return None
        if b"\0" in raw[:8192]:
            return None  # binary
        return raw.decode("utf-8", errors="replace").splitlines()


# --------------------------------------------------------------------------
# Shared helpers
# --------------------------------------------------------------------------

def _offending_env_files(tracked: Iterable[str]) -> list[str]:
    """Tracked paths that live inside an environment directory."""
    return [
        path for path in tracked
        if any(part in ENV_DIR_NAMES for part in Path(path).parts[:-1])
        or Path(path).name in ENV_DIR_NAMES
    ]


def _yaml_load(text: str) -> object:
    """Parse YAML with PyYAML when installed; otherwise signal "unavailable".

    The verifier is stdlib-only so a broken dependency install cannot disable
    the check that catches it. When PyYAML is absent, callers fall back to a
    targeted field reader that answers the same question from the text.
    """
    try:
        import yaml  # noqa: PLC0415 — optional by design
    except ImportError:
        return _YAML_UNAVAILABLE
    try:
        return yaml.safe_load(text)
    except Exception as exc:  # yaml.YAMLError and friends
        return exc


class _YamlUnavailable:
    def __repr__(self) -> str:  # pragma: no cover — debugging aid
        return "<PyYAML unavailable>"


_YAML_UNAVAILABLE = _YamlUnavailable()


def _scalar(text: str) -> str:
    return text.split("#", 1)[0].strip().strip("'\"")


# --------------------------------------------------------------------------
# Criteria
# --------------------------------------------------------------------------

def check_no_env_tracked(repo: Repository) -> CriterionResult:
    """FR-001, FR-003 — no environment file is tracked."""
    offenders = _offending_env_files(repo.tracked_files())
    if offenders:
        return CriterionResult(
            criterion_id="no-env-tracked",
            status=STATUS_FAIL,
            detail=(
                f"{len(offenders)} tracked files belong to an environment "
                f"directory (baseline was {HISTORICAL_ENV_FILE_COUNT}); "
                "tracked and ignored are independent — run the untracking step "
                "in the README"),
            evidence=tuple(offenders),
            observed={"found": len(offenders),
                      "baseline": HISTORICAL_ENV_FILE_COUNT},
        )
    return CriterionResult(
        criterion_id="no-env-tracked",
        status=STATUS_PASS,
        detail=(
            "no environment files are tracked "
            f"(0 found, was {HISTORICAL_ENV_FILE_COUNT})"),
        observed={"found": 0, "baseline": HISTORICAL_ENV_FILE_COUNT},
    )


def check_test_suite(repo: Repository) -> CriterionResult:
    """FR-012, FR-013, FR-015 — the declared runner runs, and the suite is green."""
    runner_available = subprocess.run(
        [sys.executable, "-m", TEST_RUNNER, "--version"],
        capture_output=True, text=True, cwd=repo.root, timeout=120,
    )
    if runner_available.returncode != 0:
        return CriterionResult(
            criterion_id="test-suite",
            status=STATUS_FAIL,
            detail=(
                f"declared test runner '{TEST_RUNNER}' is not installed in this "
                f"interpreter; install requirements.txt with "
                f"`{Path(sys.executable).name} -m pip install -r requirements.txt`"),
            observed={"runner": TEST_RUNNER, "installed": False},
        )

    try:
        proc = subprocess.run(
            [sys.executable, "-m", TEST_RUNNER, "-q", "-p", "no:cacheprovider"],
            capture_output=True, text=True, cwd=repo.root, timeout=900,
            # The read-only guarantee is literal, not aspirational: running the
            # suite must not leave .pytest_cache/ or __pycache__/ behind in the
            # repository it just inspected.
            env={**os.environ, "PYTHONDONTWRITEBYTECODE": "1"},
        )
    except subprocess.TimeoutExpired:
        return CriterionResult(
            criterion_id="test-suite",
            status=STATUS_UNVERIFIABLE,
            detail=(
                f"'{TEST_RUNNER}' did not finish within 900s, so the suite "
                "result is unknown"),
            observed={"runner": TEST_RUNNER, "installed": True},
        )

    output = f"{proc.stdout}\n{proc.stderr}"
    counts = _pytest_counts(output)
    passed = counts["passed"]
    failed = counts["failed"]
    errors = counts["errors"]

    if proc.returncode != 0:
        # Name the tests that failed. "3 failed" tells a reader nothing they
        # can act on, and the runner's own output is captured rather than
        # printed. Test IDs are paths, so this stays inside the rule that no
        # output field carries a detected value.
        evidence = _failed_test_ids(output)
        if not evidence:
            evidence = (f"no test IDs in the runner output; run "
                        f"`{Path(sys.executable).name} -m {TEST_RUNNER} -q` "
                        f"in {repo.root.name}/ to see it yourself",)
        return CriterionResult(
            criterion_id="test-suite",
            status=STATUS_FAIL,
            detail=(
                f"'{TEST_RUNNER}' exited {proc.returncode}: "
                f"{failed} failed, {errors} errors, {passed} passed"),
            evidence=evidence,
            observed={"runner": TEST_RUNNER, "installed": True,
                      "passed": passed, "failed": failed, "errors": errors,
                      "exit_code": proc.returncode},
        )
    return CriterionResult(
        criterion_id="test-suite",
        status=STATUS_PASS,
        detail=f"{passed} tests passed via {TEST_RUNNER}",
        observed={"runner": TEST_RUNNER, "installed": True, "passed": passed},
    )


def _pytest_counts(output: str) -> dict[str, int]:
    """Read the counts out of pytest's summary line.

    pytest orders that line by outcome and the order is not fixed: `107 passed`
    alone, or `3 failed, 104 passed, 1 warning in 20.31s`. Anchoring the pattern
    at the start of a line silently reads 0 for whichever count does not come
    first, so every count is searched for anywhere in the last summary line.
    """
    counts = {"passed": 0, "failed": 0, "errors": 0, "skipped": 0}
    for line in reversed(output.splitlines()):
        if not re.search(r"\b\d+\s+(passed|failed|error)", line):
            continue
        for number, label in re.findall(r"(\d+)\s+(passed|failed|errors?|skipped)", line):
            key = {"error": "errors", "errors": "errors"}.get(label, label)
            counts[key] = int(number)
        break
    return counts


def _failed_test_ids(output: str, limit: int = 12) -> tuple[str, ...]:
    """The `FAILED <nodeid>` lines pytest prints, in order, capped."""
    ids = re.findall(r"(?m)^FAILED\s+(\S+)", output)
    if len(ids) > limit:
        remaining = len(ids) - limit
        ids = ids[:limit] + [f"... and {remaining} more"]
    return tuple(ids)


def check_licensing_artifact(repo: Repository) -> CriterionResult:
    """FR-021 (Q3) — a root NOTICE exists and says something."""
    if not repo.exists(NOTICE):
        return CriterionResult(
            criterion_id="licensing-artifact",
            status=STATUS_FAIL,
            detail=f"{NOTICE} is absent; there is no licensing artefact",
            evidence=(NOTICE,),
        )
    if not repo.read_text(NOTICE).strip():
        return CriterionResult(
            criterion_id="licensing-artifact",
            status=STATUS_FAIL,
            detail=f"{NOTICE} exists but is empty",
            evidence=(NOTICE,),
        )
    return CriterionResult(
        criterion_id="licensing-artifact",
        status=STATUS_PASS,
        detail=f"{NOTICE} present, internal-use notice",
        evidence=(NOTICE,),
    )


def check_dependency_scanning(repo: Repository) -> CriterionResult:
    """FR-016 — dependency update scanning is *configured*.

    Activation is a hosting-side fact. GitHub publishes no repository-file
    evidence that Dependabot is switched on, so this criterion reports what it
    can actually see — configuration — and says the rest is unverifiable
    rather than guessing. The confidentiality record carries enabling it as a
    named human action.
    """
    unverifiable_tail = "(activation not verifiable from the repository)"

    if not repo.exists(DEPENDABOT):
        return CriterionResult(
            criterion_id="dependency-scanning",
            status=STATUS_FAIL,
            detail=f"{DEPENDABOT} is absent; dependency scanning is unconfigured "
                   + unverifiable_tail,
            evidence=(DEPENDABOT,),
        )

    text = repo.read_text(DEPENDABOT)
    parsed = _yaml_load(text)

    if isinstance(parsed, dict):
        ecosystems = [
            str(entry.get("package-ecosystem"))
            for entry in (parsed.get("updates") or [])
            if isinstance(entry, dict)
        ]
    elif parsed is _YAML_UNAVAILABLE:
        # PyYAML is not installed. Read the one field this criterion needs out
        # of the text rather than declaring the repository unverifiable: a
        # broken pip install must not turn a configured scanner into silence.
        ecosystems = [
            m.group(1).strip("'\"")
            for m in re.finditer(
                r"(?m)^\s*-?\s*package-ecosystem:\s*(.+?)\s*$", text)
        ]
    else:
        return CriterionResult(
            criterion_id="dependency-scanning",
            status=STATUS_FAIL,
            detail=f"{DEPENDABOT} is not valid YAML; dependency scanning cannot "
                   "be read " + unverifiable_tail,
            evidence=(DEPENDABOT,),
        )

    if not ecosystems:
        return CriterionResult(
            criterion_id="dependency-scanning",
            status=STATUS_FAIL,
            detail=f"{DEPENDABOT} declares no update ecosystem "
                   + unverifiable_tail,
            evidence=(DEPENDABOT,),
        )
    if "pip" not in ecosystems:
        return CriterionResult(
            criterion_id="dependency-scanning",
            status=STATUS_FAIL,
            detail=f"{DEPENDABOT} declares {len(ecosystems)} ecosystem(s) but no "
                   "'pip', so this project's dependencies are unwatched "
                   + unverifiable_tail,
            evidence=(DEPENDABOT,),
            observed={"ecosystems": ecosystems},
        )
    return CriterionResult(
        criterion_id="dependency-scanning",
        status=STATUS_PASS,
        detail=f"{DEPENDABOT} configured for pip " + unverifiable_tail,
        evidence=(DEPENDABOT,),
        observed={"ecosystems": ecosystems, "activation": "not_verifiable"},
    )


def _detect_secrets_block(text: str) -> Optional[str]:
    """Return the pre-commit hook block that runs detect-secrets, if any."""
    lines = text.splitlines()
    start = None
    for index, line in enumerate(lines):
        if re.search(r"(?m)^\s*-\s*repo:\s*\S*detect-secrets", line):
            start = index
        elif start is not None and re.match(r"^\s*-\s*repo:", line):
            return "\n".join(lines[start:index])
    if start is None:
        return None
    return "\n".join(lines[start:])


def _scope_covers_config_yaml(scope: str) -> bool:
    """True when a pre-commit `files:` scope covers the config YAML files.

    The scope is a regular expression, so its yaml extension arrives escaped
    and quantified (`\\.ya?ml`) rather than spelled out. Matching the literal
    `.yaml` here would reject every correctly written pattern.
    """
    return "config/" in scope and re.search(r"ya.?ml|yaml|yml", scope) is not None


def check_secret_guard(repo: Repository) -> CriterionResult:
    """FR-017, FR-020 — a commit-time secret guard, scoped to config files."""
    if not repo.exists(PRE_COMMIT_CONFIG):
        return CriterionResult(
            criterion_id="secret-guard",
            status=STATUS_FAIL,
            detail=f"{PRE_COMMIT_CONFIG} is absent; nothing runs at commit time",
            evidence=(PRE_COMMIT_CONFIG,),
        )

    block = _detect_secrets_block(repo.read_text(PRE_COMMIT_CONFIG))
    if block is None or not re.search(r"(?m)^\s*-\s*id:\s*detect-secrets", block):
        return CriterionResult(
            criterion_id="secret-guard",
            status=STATUS_FAIL,
            detail=f"{PRE_COMMIT_CONFIG} configures no detect-secrets hook",
            evidence=(PRE_COMMIT_CONFIG,),
        )

    files_match = re.search(r"(?m)^\s*files:\s*(.+)$", block)
    scope = files_match.group(1) if files_match else ""
    if not _scope_covers_config_yaml(scope):
        return CriterionResult(
            criterion_id="secret-guard",
            status=STATUS_FAIL,
            detail=(
                "the detect-secrets hook's files scope does not cover "
                f"config/*.yaml (found: {scope.strip() or 'no files filter'})"),
            evidence=(PRE_COMMIT_CONFIG,),
        )

    args_match = re.search(r"(?m)^\s*args:\s*(.+)$", block)
    args = args_match.group(1) if args_match else ""
    has_baseline = "--baseline" in args and SECRETS_BASELINE in args
    return CriterionResult(
        criterion_id="secret-guard",
        status=STATUS_PASS if has_baseline else STATUS_FAIL,
        detail=(
            f"{PRE_COMMIT_CONFIG} configures detect-secrets over config/*.yaml "
            f"with a reviewed baseline ({SECRETS_BASELINE})"
            if has_baseline else
            f"the detect-secrets hook does not use {SECRETS_BASELINE}; "
            "suppressions would be unreviewable"),
        evidence=(PRE_COMMIT_CONFIG, SECRETS_BASELINE),
    )


def check_confidentiality_record(repo: Repository) -> CriterionResult:
    """FR-021, FR-027 — the decision record exists, is complete, and is linked.

    Presence and required headings only. The verifier does not read the prose,
    judge the rationale, or second-guess an accepted exposure: approving that
    content is a human act, and automating that judgement is the failure mode
    this whole design exists to avoid.
    """
    if not repo.exists(RECORD):
        return CriterionResult(
            criterion_id="confidentiality-record",
            status=STATUS_FAIL,
            detail=f"{RECORD} is absent; the confidentiality decision is not recorded",
            evidence=(RECORD,),
        )

    text = repo.read_text(RECORD)
    headings = {m.group(1).strip() for m in re.finditer(r"(?m)^##\s+(.+?)\s*$", text)}
    missing = [s for s in REQUIRED_RECORD_SECTIONS if s not in headings]
    if missing:
        return CriterionResult(
            criterion_id="confidentiality-record",
            status=STATUS_FAIL,
            detail=(
                f"{RECORD} is missing {len(missing)} of "
                f"{len(REQUIRED_RECORD_SECTIONS)} required sections"),
            evidence=tuple(f"{RECORD} (missing: {s})" for s in missing),
            observed={"missing": missing},
        )

    if not repo.exists(README) or RECORD not in repo.read_text(README):
        return CriterionResult(
            criterion_id="confidentiality-record",
            status=STATUS_FAIL,
            detail=f"{RECORD} is complete but {README} never links to it, so it "
                   "is not findable",
            evidence=(RECORD, README),
        )

    return CriterionResult(
        criterion_id="confidentiality-record",
        status=STATUS_PASS,
        detail=f"{RECORD} present and linked from {README}",
        evidence=(RECORD, README),
    )


def _live_project_entries(repo: Repository) -> list[str]:
    """Any uncommented live-metadata key anywhere in `config/projects.yaml`.

    Scoped to the file, not to one block within it. An earlier version followed
    the contract's wording literally and scanned only the `repos:` block, which
    left a hole: a live `budget:` under `overrides:` passed, even though FR-023
    forbids real project names with budgets without qualification. Narrower than
    the requirement it implements is not a safe default for a security control.

    Widening costs nothing in false positives. `overrides:` legitimately holds
    `activity_window_days`, which is not one of `LIVE_PROJECT_KEYS`, and the rule
    still asks whether a key is *commented* rather than which file it sits in, so
    FR-030 compliance is unchanged.
    """
    if not repo.exists(PROJECTS_CONFIG):
        return []
    offenders: list[str] = []
    for number, raw in enumerate(repo.read_text(PROJECTS_CONFIG).splitlines(), 1):
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        key = _scalar(stripped).split(":", 1)[0].strip()
        if key in LIVE_PROJECT_KEYS:
            offenders.append(f"{PROJECTS_CONFIG}:{number}  {key}")
    return offenders


def _accepted_exposure_identifiers(record_text: str) -> list[str]:
    """Identifiers listed in the record's Accepted Exposures table, in order.

    The header row is skipped structurally — a table row is a header when the
    line beneath it is a separator — rather than by matching the word
    "Identifier", so renaming a column cannot silently start counting as an
    exposure.
    """
    identifiers: list[str] = []
    in_section = False
    lines = record_text.splitlines()
    for position, raw in enumerate(lines):
        heading = re.match(r"^##\s+(.+?)\s*$", raw)
        if heading:
            in_section = heading.group(1).strip() == "Accepted Exposures"
            continue
        if not in_section or not raw.strip().startswith("|"):
            continue
        cells = [c.strip() for c in raw.strip().strip("|").split("|")]
        if len(cells) < 2:
            continue
        identifier = cells[0].strip("`").strip()
        if not identifier or set(identifier) <= set("-: "):
            continue
        following = lines[position + 1] if position + 1 < len(lines) else ""
        following_cells = [
            c.strip() for c in following.strip().strip("|").split("|")
        ] if following.strip().startswith("|") else []
        if following_cells and all(set(c) <= set("-: ") for c in following_cells):
            continue  # header row: the line below it is the separator
        identifiers.append(identifier)
    return identifiers


def check_no_real_data(repo: Repository) -> CriterionResult:
    """FR-023, FR-024, FR-025 — the no-real-data policy, held by content.

    Two deterministic parts, no classifier (research.md D7). A heuristic
    "does this look like real project data?" check would have to guess what
    real looks like, and a check that guesses trains people to ignore it.
    """
    findings: list[str] = []

    for path, lines in repo.tracked_text_files():
        for number, line in enumerate(lines, 1):
            for identifier in DENIED_IDENTIFIERS:
                if identifier in line:
                    # Path, line, pattern — never the value.
                    findings.append(f"{path}:{number}  denied identifier ({len(identifier)} chars)")

    for path in repo.tracked_files():
        if path.split("/")[0] == "reports":
            findings.append(f"{path}  generated run output is tracked")

    findings.extend(_live_project_entries(repo))

    if repo.exists(RECORD):
        # The record's own text is excluded from the presence search: an
        # exposure names an identifier that is committed *elsewhere*, and
        # letting the record satisfy its own check would make every stale
        # exposure look current forever.
        elsewhere = [
            (path, lines) for path, lines in repo.tracked_text_files()
            if path != RECORD
        ]
        for index, identifier in enumerate(
                _accepted_exposure_identifiers(repo.read_text(RECORD)), 1):
            if not any(identifier in line for _, lines in elsewhere for line in lines):
                # An exposure for an identifier that is gone is a gap in the
                # denylist dressed up as a decision. Reported by position, not
                # by value.
                findings.append(
                    f"accepted exposure #{index} is stale: the identifier it "
                    "covers no longer appears in tracked content")

    if findings:
        return CriterionResult(
            criterion_id="no-real-data",
            status=STATUS_FAIL,
            detail=(
                f"{len(findings)} no-real-data violation(s) in tracked content: "
                "live run output, real project metadata, and denied identifiers "
                "are all out of bounds here"),
            evidence=tuple(findings),
            observed={"violations": len(findings)},
        )
    return CriterionResult(
        criterion_id="no-real-data",
        status=STATUS_PASS,
        detail=(
            f"no denied identifiers, live run output, or live project metadata "
            f"in {len(repo.tracked_files())} tracked files"),
        observed={"tracked_files": len(repo.tracked_files()),
                  "denied_identifiers": len(DENIED_IDENTIFIERS)},
    )


# --------------------------------------------------------------------------
# Registry — declared order is the output order, never sorted at runtime
# --------------------------------------------------------------------------

def _criterion(cid, label, requirements, check):
    return Criterion(
        id=cid,
        label=label,
        requirements=tuple(requirements),
        determination="observed",
        cannot_determine_action="report_unverifiable",
        check=check,
    )


CRITERIA: tuple[Criterion, ...] = (
    _criterion("no-env-tracked",
               "no environment files are tracked",
               ("FR-001", "FR-003"),
               check_no_env_tracked),
    _criterion("test-suite",
               "the declared test runner runs the suite green",
               ("FR-012", "FR-013", "FR-015"),
               check_test_suite),
    _criterion("licensing-artifact",
               "an internal-use notice states the licensing position",
               ("Q3", "FR-021"),
               check_licensing_artifact),
    _criterion("dependency-scanning",
               "dependency update scanning is configured",
               ("FR-016",),
               check_dependency_scanning),
    _criterion("secret-guard",
               "a commit-time secret guard is configured for config files",
               ("FR-017", "FR-020"),
               check_secret_guard),
    _criterion("confidentiality-record",
               "the confidentiality decision is recorded and linked",
               ("FR-021", "FR-027"),
               check_confidentiality_record),
    _criterion("no-real-data",
               "no real Navadhiti data is committed",
               ("FR-023", "FR-024", "FR-025"),
               check_no_real_data),
)


def _validated_registry(criteria: Iterable[Criterion]) -> tuple[Criterion, ...]:
    registry = tuple(criteria)
    seen: set[str] = set()
    for criterion in registry:
        if criterion.id in seen:
            raise VerifierCannotStart(
                f"criterion id {criterion.id!r} is registered twice; a repeated "
                "id makes history comparisons meaningless")
        seen.add(criterion.id)
    return registry


def evaluate(repo: Repository,
             registry: Iterable[Criterion] = CRITERIA) -> BaselineReport:
    results: list[CriterionResult] = []
    for criterion in _validated_registry(registry):
        results.append(criterion.check(repo))

    # A check that cannot run is not a check that passed: any fail or
    # unverifiable result fails the run.
    verdict = (STATUS_PASS if all(r.status == STATUS_PASS for r in results)
               else STATUS_FAIL)
    return BaselineReport(
        criteria=tuple(results),
        verdict=verdict,
        commit=repo.commit_sha(),
        generated_at=datetime.now(timezone.utc).isoformat(timespec="seconds"),
        blocking=False,
    )


# --------------------------------------------------------------------------
# Output
# --------------------------------------------------------------------------

_STATUS_WIDTH = max(len(s) for s in (STATUS_PASS, STATUS_FAIL, STATUS_UNVERIFIABLE)) + 1
_ID_WIDTH = max(len(c.id) for c in CRITERIA) + 1
_EVIDENCE_INDENT = " " * (_STATUS_WIDTH + _ID_WIDTH + 1)


def format_report(report: BaselineReport) -> str:
    """Render the report exactly as the contract specifies.

    `generated_at` is deliberately absent: it is the only field that varies
    between two runs against the same commit, and printing it would make the
    output non-idempotent for no informational gain.
    """
    lines = ["navadhiti hygiene — repository baseline"]
    lines.append(f"commit: {report.commit or 'absent (not a git repository)'}")
    lines.append("")

    for result in report.criteria:
        lines.append(f"  {result.status:<{_STATUS_WIDTH}}"
                     f"{result.criterion_id:<{_ID_WIDTH}} {result.detail}")
        for item in result.evidence:
            lines.append(f"{_EVIDENCE_INDENT}{item}")

    total = len(report.criteria)
    if report.verdict == STATUS_PASS:
        lines.append(f"verdict: PASS ({total} of {total} criteria passed)")
    else:
        lines.append(
            f"verdict: FAIL ({report.failed} of {total} criteria failed)")
    lines.append(DISCLAIMER)
    return "\n".join(lines)


# --------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------

def main(argv: Optional[list[str]] = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if argv:
        print(
            "verify_baseline.py takes no arguments: local and CI must run the "
            "same command against the same criterion list, and every optional "
            "flag is a chance for the two to disagree.",
            file=sys.stderr,
        )
        return EXIT_CANNOT_RUN

    if sys.version_info < (3, 8):
        print("verify_baseline.py requires Python 3.8 or newer", file=sys.stderr)
        return EXIT_CANNOT_RUN

    try:
        repo = Repository(REPO_ROOT)
        if not (repo.root / ".git").exists():
            raise VerifierCannotStart(
                f"{repo.root} is not a git repository")
        # Resolves the tracked-file list; a repository without commits has
        # nothing to verify and must not read as healthy.
        repo.tracked_files()
        report = evaluate(repo)
    except VerifierCannotStart as exc:
        print("navadhiti hygiene — repository baseline", file=sys.stderr)
        print(f"verifier could not run: {exc}", file=sys.stderr)
        print(
            f"this says nothing about the repository's health; exit "
            f"{EXIT_CANNOT_RUN} means 'I could not look', not 'it is fine'",
            file=sys.stderr,
        )
        return EXIT_CANNOT_RUN
    except Exception as exc:  # noqa: BLE001 — never report a crash as health
        print(f"verifier could not run: {type(exc).__name__}: {exc}",
              file=sys.stderr)
        return EXIT_CANNOT_RUN

    print(format_report(report))
    return EXIT_PASS if report.verdict == STATUS_PASS else EXIT_FAIL


if __name__ == "__main__":
    os.chdir(REPO_ROOT)
    sys.exit(main())